upstream backend {
    server 51.79.173.142:30000;
}
upstream backendv2 {
    server 51.79.173.142:30003;
}

server {
  listen        $PORT;
  listen        [::]:$PORT;
  server_name   _;

  # Increase max upload size to handle large file uploads
  client_max_body_size 150M;

  # add_header 'Access-Control-Allow-Origin' '*';
  # add_header 'Access-Control-Allow-Credentials' 'true';
  # add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
  # add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_pass http://backend;
    proxy_set_header Host $host;
    proxy_set_header X-Real-Ip $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # To preserve the original host and SSL settings in the proxy request
    # proxy_set_header X-Forwarded-Host $http_host;
    # proxy_set_header X-Forwarded-Port $server_port;
    # proxy_set_header X-Forwarded-Proto $scheme;

  }

  location /api-v2/ {
    proxy_pass http://backendv2/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-Ip $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # To preserve the original host and SSL settings in the proxy request
    # proxy_set_header X-Forwarded-Host $http_host;
    # proxy_set_header X-Forwarded-Port $server_port;
    # proxy_set_header X-Forwarded-Proto $scheme;

  }

}

