name: Develop

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    name: Setup Gcloud Account
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} # TODO: update Google Cloud project id
      SERVICE: ${{ vars.GCP_CR_SERVICE_NAME }} # TODO: update Cloud Run service name
      REGION: ${{ vars.GCP_REGION }} # TODO: update Cloud Run service region
      IMAGE_NAME: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_APP_NAME }}
    steps:
      - name: Login
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Deploy Docker image
        run: gcloud run deploy ${{ env.SERVICE }} --image ${{ env.IMAGE_NAME }} --region ${{ env.REGION }} --platform managed --allow-unauthenticated
